Download postcard
generated-online/generated.online pull request #117
Opened 2020-12-19 21:05 UTC by fellnerse

without timer, the background is not yet loaded -.- took me way too long to figure out
still need to also download just the image of the text maybe

2020-12-19 21:07 UTC, mowolf submitted a review, later dismissed

2020-12-19 21:15 UTC, fellnerse commented
add loading animation

2020-12-19 21:15 UTC, fellnerse commented
add nice download image to download button

2020-12-20 23:16 UTC, mowolf commented
Super cool!

Es wird der Text nicht ganz richtig gerendert. Und es könnte verwirrent sein wenn man ausversehen da klickt und man das nicht checkt dann da weitergeleitet wird. Wir könnten versuchen anstatt es weiterzuleiten auf die neue seite das in der seite zu machen. Postkarten Element in Groß wird unten an das DOM gehängt und gescreenshottet und sofort entfernt. So sollte der Nutzer das nicht mitbekommen, man müsste nichtmehr warten und man müsste die ganzen sachen nicht doppelt laden.

RENDER:
![postcard-front_qqJeGd6PExVESrtP1qVk_](https://user-images.githubusercontent.com/32100482/102726722-5ee54e80-4321-11eb-8653-5b763c9e5e80.png)

Wie es gehört:
<img width="1137" alt="Bildschirmfoto 2020-12-21 um 00 13 27" src="https://user-images.githubusercontent.com/32100482/102726728-66a4f300-4321-11eb-872c-8574e50f7749.png">

2020-12-20 23:16 UTC, mowolf requested changes
see comment

2020-12-21 09:30 UTC, fellnerse commented
ah interessant das ist mir nicht aufgefallen;
also warum es mit den postkarten auf der recipe seite nicht geklappt hat
liegt an dem css transform, das wird von dem tool nicht unterstütz;

da sieht es so aus als würde etwas css fehlen? der zeilenabstand und
anfangs end padding

On Mon, 21 Dec 2020 at 00:16, Moritz Wolf <notifications@github.com> wrote:

> *@mowolf* requested changes on this pull request.
>
> see comment
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/generated-online/generated.online/pull/117#pullrequestreview-556071073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ2CVCHGM2QJ4IGQVF6IBR3SV2AWBANCNFSM4VCR3WGQ>
> .
>

2020-12-21 09:33 UTC, fellnerse commented
thats extremly strange; it looks like during the rendering the span is converted to a div? -> thus the block backgorund instead of span background

2020-12-21 09:39 UTC, fellnerse commented
i would suggest moving this to the same page is something for another PR

2020-12-22 10:36 UTC, fellnerse commented
fixed this issue but now there is small line between spans, dont know how to fix this

2020-12-22 20:36 UTC, mowolf approved these changes
Cool!

2020-12-22 21:00 UTC, merged