Make search nice
generated-online/generated.online pull request #122
Opened 2020-12-20 20:41 UTC by fellnerse

looks cool now with emojis in the refinement list

still need:
- [] vote count in results
- [] results alignment
- [] search without text?

2020-12-20 23:11 UTC, mowolf requested changes
Finde ich sehr cool! Wir sollten anstatt den ratings wenn es noch nicht gerated wurde was anderes anzeigen. Zudem machen wir da ja keine Firebase queries also sind die immer auf 0?

2020-12-21 09:27 UTC, fellnerse commented
Ja genau ich wollte die eigentlich noch nachladen per firebase; ist jetzt
die frage ob wir sagen lassen wir weg, oder halt nicht;
fände es schon nice eigentlich die mit anzuzeigen

On Mon, 21 Dec 2020 at 00:11, Moritz Wolf <notifications@github.com> wrote:

> *@mowolf* requested changes on this pull request.
>
> Finde ich sehr cool! Wir sollten anstatt den ratings wenn es noch nicht
> gerated wurde was anderes anzeigen. Zudem machen wir da ja keine Firebase
> queries also sind die immer auf 0?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/generated-online/generated.online/pull/122#pullrequestreview-556070658>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ2CVCHDAEKMLMOCHVRQSRTSV2ACFANCNFSM4VDLR5QQ>
> .
>

2020-12-21 11:25 UTC, mowolf submitted a review, later dismissed

2020-12-21 12:29 UTC, mowolf approved these changes

2020-12-22 08:41 UTC, fellnerse commented
würde es so mergen

2020-12-22 20:37 UTC, mowolf approved these changes
Nice nice!

2020-12-23 00:23 UTC, mowolf approved these changes

2020-12-23 07:19 UTC, merged