background looks nice now; also button is better
generated-online/generated.online pull request #47
Opened 2020-11-23 17:34 UTC by fellnerse

2020-11-23 18:29 UTC, fellnerse commented
@mowolf

2020-11-24 14:35 UTC, mowolf commented on frontend/recepies.generated.online/src/components/EmojieBackground.vue
> +            this.matchingEmos = this.matchingEmos.concat(this.matchingEmos)
We should really do this more intelligetly

2020-11-24 14:35 UTC, mowolf commented on frontend/recepies.generated.online/src/components/Voting.vue
> +                <span class="womanCook">👩‍🍳</span>
Did you change the favicon to the womanCook icon as well?

2020-11-24 14:36 UTC, mowolf commented on frontend/recepies.generated.online/src/views/Recipe.vue
> +    <div v-for="recipe in recipes" :key="recipe.id" class="recipe">
Should we refactor, and only work with one recipe?

2020-11-24 14:38 UTC, mowolf requested changes
check comments

2020-11-24 14:39 UTC, mowolf commented on frontend/recepies.generated.online/src/components/EmojieBackground.vue
> +            this.matchingEmos = this.matchingEmos.concat(this.matchingEmos)
Maybe we can repeat it in css, this would remove the heavy browser load of 1000+ floating emojies? I don't know if this exists though

2020-11-24 16:16 UTC, fellnerse commented on frontend/recepies.generated.online/src/components/Voting.vue
> +                <span class="womanCook">👩‍🍳</span>
yes, lol now its possible to do this with emojis as well

2020-11-24 17:08 UTC, fellnerse commented on frontend/recepies.generated.online/src/views/Recipe.vue
> +    <div v-for="recipe in recipes" :key="recipe.id" class="recipe">
i think this does not work

2020-11-28 15:07 UTC, mowolf approved these changes

2020-11-28 15:08 UTC, merged